/*
 * UnicodeArabicPresentation.cpp - Arabic letter shaping lookup table
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by components/focus/tools/unicodedata/generate_arabic.py
 *
 * Arabic letters take different forms depending on position:
 * - Isolated: standalone
 * - Initial: beginning of word
 * - Medial: middle of word
 * - Final: end of word
 *
 * Note: Lam-Alef ligatures are NOT in this table.
 * Implementations must handle these manually:
 *   U+0644 + U+0622 => U+FEF5 (isolated) / U+FEF6 (final)
 *   U+0644 + U+0623 => U+FEF7 (isolated) / U+FEF8 (final)
 *   U+0644 + U+0625 => U+FEF9 (isolated) / U+FEFA (final)
 *   U+0644 + U+0627 => U+FEFB (isolated) / U+FEFC (final)
 */

#include "UnicodeArabicPresentation.hpp"

namespace focus {

namespace UnicodeArabicPresentation {

namespace {

// Base range: U+0621 to U+06D2
static constexpr UNICODE_CODEPOINT BASE_START = 0x0621;
static constexpr UNICODE_CODEPOINT BASE_END = 0x06D2;

// Lookup table: [codepoint - BASE_START][form]
// Forms: 0=Isolated, 1=Initial, 2=Medial, 3=Final
// Value of 0 means form not available
static const uint16_t presentationForms[][4] = {
    {0xFE80, 0, 0, 0}, // U+0621
    {0xFE81, 0, 0, 0xFE82}, // U+0622
    {0xFE83, 0, 0, 0xFE84}, // U+0623
    {0xFE85, 0, 0, 0xFE86}, // U+0624
    {0xFE87, 0, 0, 0xFE88}, // U+0625
    {0xFE89, 0xFE8B, 0xFE8C, 0xFE8A}, // U+0626
    {0xFE8D, 0, 0, 0xFE8E}, // U+0627
    {0xFE8F, 0xFE91, 0xFE92, 0xFE90}, // U+0628
    {0xFE93, 0, 0, 0xFE94}, // U+0629
    {0xFE95, 0xFE97, 0xFE98, 0xFE96}, // U+062A
    {0xFE99, 0xFE9B, 0xFE9C, 0xFE9A}, // U+062B
    {0xFE9D, 0xFE9F, 0xFEA0, 0xFE9E}, // U+062C
    {0xFEA1, 0xFEA3, 0xFEA4, 0xFEA2}, // U+062D
    {0xFEA5, 0xFEA7, 0xFEA8, 0xFEA6}, // U+062E
    {0xFEA9, 0, 0, 0xFEAA}, // U+062F
    {0xFEAB, 0, 0, 0xFEAC}, // U+0630
    {0xFEAD, 0, 0, 0xFEAE}, // U+0631
    {0xFEAF, 0, 0, 0xFEB0}, // U+0632
    {0xFEB1, 0xFEB3, 0xFEB4, 0xFEB2}, // U+0633
    {0xFEB5, 0xFEB7, 0xFEB8, 0xFEB6}, // U+0634
    {0xFEB9, 0xFEBB, 0xFEBC, 0xFEBA}, // U+0635
    {0xFEBD, 0xFEBF, 0xFEC0, 0xFEBE}, // U+0636
    {0xFEC1, 0xFEC3, 0xFEC4, 0xFEC2}, // U+0637
    {0xFEC5, 0xFEC7, 0xFEC8, 0xFEC6}, // U+0638
    {0xFEC9, 0xFECB, 0xFECC, 0xFECA}, // U+0639
    {0xFECD, 0xFECF, 0xFED0, 0xFECE}, // U+063A
    {0, 0, 0, 0}, // U+063B
    {0, 0, 0, 0}, // U+063C
    {0, 0, 0, 0}, // U+063D
    {0, 0, 0, 0}, // U+063E
    {0, 0, 0, 0}, // U+063F
    {0, 0, 0, 0}, // U+0640
    {0xFED1, 0xFED3, 0xFED4, 0xFED2}, // U+0641
    {0xFED5, 0xFED7, 0xFED8, 0xFED6}, // U+0642
    {0xFED9, 0xFEDB, 0xFEDC, 0xFEDA}, // U+0643
    {0xFEDD, 0xFEDF, 0xFEE0, 0xFEDE}, // U+0644
    {0xFEE1, 0xFEE3, 0xFEE4, 0xFEE2}, // U+0645
    {0xFEE5, 0xFEE7, 0xFEE8, 0xFEE6}, // U+0646
    {0xFEE9, 0xFEEB, 0xFEEC, 0xFEEA}, // U+0647
    {0xFEED, 0, 0, 0xFEEE}, // U+0648
    {0xFEEF, 0, 0, 0xFEF0}, // U+0649
    {0xFEF1, 0xFEF3, 0xFEF4, 0xFEF2}, // U+064A
    {0xFE70, 0, 0, 0}, // U+064B
    {0xFE72, 0, 0, 0}, // U+064C
    {0xFE74, 0, 0, 0}, // U+064D
    {0xFE76, 0, 0xFE77, 0}, // U+064E
    {0xFE78, 0, 0xFE79, 0}, // U+064F
    {0xFE7A, 0, 0xFE7B, 0}, // U+0650
    {0xFE7C, 0, 0xFE7D, 0}, // U+0651
    {0xFE7E, 0, 0xFE7F, 0}, // U+0652
    {0, 0, 0, 0}, // U+0653
    {0, 0, 0, 0}, // U+0654
    {0, 0, 0, 0}, // U+0655
    {0, 0, 0, 0}, // U+0656
    {0, 0, 0, 0}, // U+0657
    {0, 0, 0, 0}, // U+0658
    {0, 0, 0, 0}, // U+0659
    {0, 0, 0, 0}, // U+065A
    {0, 0, 0, 0}, // U+065B
    {0, 0, 0, 0}, // U+065C
    {0, 0, 0, 0}, // U+065D
    {0, 0, 0, 0}, // U+065E
    {0, 0, 0, 0}, // U+065F
    {0, 0, 0, 0}, // U+0660
    {0, 0, 0, 0}, // U+0661
    {0, 0, 0, 0}, // U+0662
    {0, 0, 0, 0}, // U+0663
    {0, 0, 0, 0}, // U+0664
    {0, 0, 0, 0}, // U+0665
    {0, 0, 0, 0}, // U+0666
    {0, 0, 0, 0}, // U+0667
    {0, 0, 0, 0}, // U+0668
    {0, 0, 0, 0}, // U+0669
    {0, 0, 0, 0}, // U+066A
    {0, 0, 0, 0}, // U+066B
    {0, 0, 0, 0}, // U+066C
    {0, 0, 0, 0}, // U+066D
    {0, 0, 0, 0}, // U+066E
    {0, 0, 0, 0}, // U+066F
    {0, 0, 0, 0}, // U+0670
    {0xFB50, 0, 0, 0xFB51}, // U+0671
    {0, 0, 0, 0}, // U+0672
    {0, 0, 0, 0}, // U+0673
    {0, 0, 0, 0}, // U+0674
    {0, 0, 0, 0}, // U+0675
    {0, 0, 0, 0}, // U+0676
    {0xFBDD, 0, 0, 0}, // U+0677
    {0, 0, 0, 0}, // U+0678
    {0xFB66, 0xFB68, 0xFB69, 0xFB67}, // U+0679
    {0xFB5E, 0xFB60, 0xFB61, 0xFB5F}, // U+067A
    {0xFB52, 0xFB54, 0xFB55, 0xFB53}, // U+067B
    {0, 0, 0, 0}, // U+067C
    {0, 0, 0, 0}, // U+067D
    {0xFB56, 0xFB58, 0xFB59, 0xFB57}, // U+067E
    {0xFB62, 0xFB64, 0xFB65, 0xFB63}, // U+067F
    {0xFB5A, 0xFB5C, 0xFB5D, 0xFB5B}, // U+0680
    {0, 0, 0, 0}, // U+0681
    {0, 0, 0, 0}, // U+0682
    {0xFB76, 0xFB78, 0xFB79, 0xFB77}, // U+0683
    {0xFB72, 0xFB74, 0xFB75, 0xFB73}, // U+0684
    {0, 0, 0, 0}, // U+0685
    {0xFB7A, 0xFB7C, 0xFB7D, 0xFB7B}, // U+0686
    {0xFB7E, 0xFB80, 0xFB81, 0xFB7F}, // U+0687
    {0xFB88, 0, 0, 0xFB89}, // U+0688
    {0, 0, 0, 0}, // U+0689
    {0, 0, 0, 0}, // U+068A
    {0, 0, 0, 0}, // U+068B
    {0xFB84, 0, 0, 0xFB85}, // U+068C
    {0xFB82, 0, 0, 0xFB83}, // U+068D
    {0xFB86, 0, 0, 0xFB87}, // U+068E
    {0, 0, 0, 0}, // U+068F
    {0, 0, 0, 0}, // U+0690
    {0xFB8C, 0, 0, 0xFB8D}, // U+0691
    {0, 0, 0, 0}, // U+0692
    {0, 0, 0, 0}, // U+0693
    {0, 0, 0, 0}, // U+0694
    {0, 0, 0, 0}, // U+0695
    {0, 0, 0, 0}, // U+0696
    {0, 0, 0, 0}, // U+0697
    {0xFB8A, 0, 0, 0xFB8B}, // U+0698
    {0, 0, 0, 0}, // U+0699
    {0, 0, 0, 0}, // U+069A
    {0, 0, 0, 0}, // U+069B
    {0, 0, 0, 0}, // U+069C
    {0, 0, 0, 0}, // U+069D
    {0, 0, 0, 0}, // U+069E
    {0, 0, 0, 0}, // U+069F
    {0, 0, 0, 0}, // U+06A0
    {0, 0, 0, 0}, // U+06A1
    {0, 0, 0, 0}, // U+06A2
    {0, 0, 0, 0}, // U+06A3
    {0xFB6A, 0xFB6C, 0xFB6D, 0xFB6B}, // U+06A4
    {0, 0, 0, 0}, // U+06A5
    {0xFB6E, 0xFB70, 0xFB71, 0xFB6F}, // U+06A6
    {0, 0, 0, 0}, // U+06A7
    {0, 0, 0, 0}, // U+06A8
    {0xFB8E, 0xFB90, 0xFB91, 0xFB8F}, // U+06A9
    {0, 0, 0, 0}, // U+06AA
    {0, 0, 0, 0}, // U+06AB
    {0, 0, 0, 0}, // U+06AC
    {0xFBD3, 0xFBD5, 0xFBD6, 0xFBD4}, // U+06AD
    {0, 0, 0, 0}, // U+06AE
    {0xFB92, 0xFB94, 0xFB95, 0xFB93}, // U+06AF
    {0, 0, 0, 0}, // U+06B0
    {0xFB9A, 0xFB9C, 0xFB9D, 0xFB9B}, // U+06B1
    {0, 0, 0, 0}, // U+06B2
    {0xFB96, 0xFB98, 0xFB99, 0xFB97}, // U+06B3
    {0, 0, 0, 0}, // U+06B4
    {0, 0, 0, 0}, // U+06B5
    {0, 0, 0, 0}, // U+06B6
    {0, 0, 0, 0}, // U+06B7
    {0, 0, 0, 0}, // U+06B8
    {0, 0, 0, 0}, // U+06B9
    {0xFB9E, 0, 0, 0xFB9F}, // U+06BA
    {0xFBA0, 0xFBA2, 0xFBA3, 0xFBA1}, // U+06BB
    {0, 0, 0, 0}, // U+06BC
    {0, 0, 0, 0}, // U+06BD
    {0xFBAA, 0xFBAC, 0xFBAD, 0xFBAB}, // U+06BE
    {0, 0, 0, 0}, // U+06BF
    {0xFBA4, 0, 0, 0xFBA5}, // U+06C0
    {0xFBA6, 0xFBA8, 0xFBA9, 0xFBA7}, // U+06C1
    {0, 0, 0, 0}, // U+06C2
    {0, 0, 0, 0}, // U+06C3
    {0, 0, 0, 0}, // U+06C4
    {0xFBE0, 0, 0, 0xFBE1}, // U+06C5
    {0xFBD9, 0, 0, 0xFBDA}, // U+06C6
    {0xFBD7, 0, 0, 0xFBD8}, // U+06C7
    {0xFBDB, 0, 0, 0xFBDC}, // U+06C8
    {0xFBE2, 0, 0, 0xFBE3}, // U+06C9
    {0, 0, 0, 0}, // U+06CA
    {0xFBDE, 0, 0, 0xFBDF}, // U+06CB
    {0xFBFC, 0xFBFE, 0xFBFF, 0xFBFD}, // U+06CC
    {0, 0, 0, 0}, // U+06CD
    {0, 0, 0, 0}, // U+06CE
    {0, 0, 0, 0}, // U+06CF
    {0xFBE4, 0xFBE6, 0xFBE7, 0xFBE5}, // U+06D0
    {0, 0, 0, 0}, // U+06D1
    {0xFBAE, 0, 0, 0xFBAF}, // U+06D2
};

} // anonymous namespace

bool isShapeable(UNICODE_CODEPOINT cp) {
    if (cp < BASE_START || cp > BASE_END) return false;
    // Check if any form exists
    const uint16_t* forms = presentationForms[cp - BASE_START];
    return forms[0] != 0;  // Isolated form indicates shapeability
}

UNICODE_CODEPOINT getForm(UNICODE_CODEPOINT base, Form form) {
    if (base < BASE_START || base > BASE_END) return 0;
    return presentationForms[base - BASE_START][static_cast<int>(form)];
}

} // namespace UnicodeArabicPresentation

}  // namespace focus
