; Focus MP3 player example — PyGamer and PyPortal targets.
; PlatformIO only; does not work in Arduino IDE (requires custom build flags)
[env]
platform = atmelsam
framework = arduino
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -frtti
    -fexceptions
    -Isrc
    -I../../include/core
    -I../../include/settings
    -I../../include/text
    -I../../include/locale
    -I../../include/views
    -I../../include/controls
    -I../../include/viewcontrollers
; We only need the classic USB-CDC Serial, so we can skip TinyUSB.
lib_ignore = Adafruit TinyUSB Library
monitor_speed = 115200

[env:pygamer]
board = adafruit_pygamer_m4
build_src_filter = +<app/> +<platform/samd/> -<platform/samd/pyportal/>
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.0
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit BusIO@^1.14.0
    adafruit/Adafruit Zero DMA Library@^1.1.0
    adafruit/Adafruit MP3@^1.2.6
    adafruit/SdFat - Adafruit Fork@^2.2.3
    symlink://../..

[env:pyportal]
board = adafruit_pyportal_m4
build_src_filter = +<app/> +<platform/samd/> -<platform/samd/pygamer/>
lib_deps =
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit BusIO@^1.14.0
    adafruit/Adafruit Zero DMA Library@^1.1.0
    adafruit/Adafruit TouchScreen@^1.1.4
    adafruit/Adafruit MP3@^1.2.6
    adafruit/SdFat - Adafruit Fork@^2.2.3
    symlink://../..
