#!/usr/bin/env python3
# MIT License
#
# Copyright (c) 2026 Joey Castillo
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""
Generate UnicodeMappings.cpp - case conversion and mirroring tables.

Parses UnicodeData.txt and BidiMirroring.txt to extract:
- Uppercase mappings
- Lowercase mappings
- Titlecase mappings
- Bidi mirroring mappings

Usage:
    python3 generate_mappings.py [--output PATH]
"""

import argparse
import os

def parse_unicode_data():
    """Parse UnicodeData.txt for case mappings."""
    uppercase = []
    lowercase = []
    titlecase = []

    with open('UnicodeData.txt', 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            fields = line.split(';')
            if len(fields) < 15:
                continue

            try:
                codepoint = int(fields[0], 16)
            except ValueError:
                continue

            # Fields 12, 13, 14 are uppercase, lowercase, titlecase mappings
            if fields[12]:
                try:
                    upper = int(fields[12], 16)
                    uppercase.append((codepoint, upper))
                except ValueError:
                    pass

            if fields[13]:
                try:
                    lower = int(fields[13], 16)
                    lowercase.append((codepoint, lower))
                except ValueError:
                    pass

            if fields[14]:
                try:
                    title = int(fields[14], 16)
                    titlecase.append((codepoint, title))
                except ValueError:
                    pass

    return uppercase, lowercase, titlecase

def parse_bidi_mirroring():
    """Parse BidiMirroring.txt for mirroring mappings."""
    mirror = []

    with open('BidiMirroring.txt', 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            # Remove comments
            if '#' in line:
                line = line.split('#')[0].strip()

            if ';' not in line:
                continue

            parts = line.split(';')
            if len(parts) < 2:
                continue

            try:
                source = int(parts[0].strip(), 16)
                target = int(parts[1].strip(), 16)
                mirror.append((source, target))
            except ValueError:
                continue

    return mirror

def generate_cpp(uppercase, lowercase, titlecase, mirror, output_path):
    """Generate the C++ source file."""

    # Sort all mappings by source codepoint for binary search
    uppercase.sort(key=lambda x: x[0])
    lowercase.sort(key=lambda x: x[0])
    titlecase.sort(key=lambda x: x[0])
    mirror.sort(key=lambda x: x[0])

    lines = []
    lines.append('/*')
    lines.append(' * UnicodeMappings.cpp - Unicode case conversion and mirroring tables')
    lines.append(' *')
    lines.append(' * AUTO-GENERATED FILE - DO NOT EDIT')
    lines.append(' * Generated by tools/unicodedata/generate_mappings.py')
    lines.append(' */')
    lines.append('')
    lines.append('#include "UnicodeMappings.hpp"')
    lines.append('#include <algorithm>')
    lines.append('')
    lines.append('namespace UnicodeMappings {')
    lines.append('')
    lines.append('namespace {')
    lines.append('')
    lines.append('struct Mapping {')
    lines.append('    uint32_t source;')
    lines.append('    uint32_t target;')
    lines.append('};')
    lines.append('')

    # Generate uppercase table
    lines.append(f'static const Mapping uppercaseTable[] = {{')
    for src, tgt in uppercase:
        lines.append(f'    {{0x{src:04X}, 0x{tgt:04X}}},')
    lines.append('};')
    lines.append(f'static constexpr size_t uppercaseCount = {len(uppercase)};')
    lines.append('')

    # Generate lowercase table
    lines.append(f'static const Mapping lowercaseTable[] = {{')
    for src, tgt in lowercase:
        lines.append(f'    {{0x{src:04X}, 0x{tgt:04X}}},')
    lines.append('};')
    lines.append(f'static constexpr size_t lowercaseCount = {len(lowercase)};')
    lines.append('')

    # Generate titlecase table
    lines.append(f'static const Mapping titlecaseTable[] = {{')
    for src, tgt in titlecase:
        lines.append(f'    {{0x{src:04X}, 0x{tgt:04X}}},')
    lines.append('};')
    lines.append(f'static constexpr size_t titlecaseCount = {len(titlecase)};')
    lines.append('')

    # Generate mirror table
    lines.append(f'static const Mapping mirrorTable[] = {{')
    for src, tgt in mirror:
        lines.append(f'    {{0x{src:04X}, 0x{tgt:04X}}},')
    lines.append('};')
    lines.append(f'static constexpr size_t mirrorCount = {len(mirror)};')
    lines.append('')

    # Binary search helper
    lines.append('static UNICODE_CODEPOINT lookupMapping(const Mapping* table, size_t count, UNICODE_CODEPOINT cp) {')
    lines.append('    size_t left = 0;')
    lines.append('    size_t right = count;')
    lines.append('    while (left < right) {')
    lines.append('        size_t mid = left + (right - left) / 2;')
    lines.append('        if (table[mid].source < cp) {')
    lines.append('            left = mid + 1;')
    lines.append('        } else if (table[mid].source > cp) {')
    lines.append('            right = mid;')
    lines.append('        } else {')
    lines.append('            return table[mid].target;')
    lines.append('        }')
    lines.append('    }')
    lines.append('    return cp;  // No mapping found, return original')
    lines.append('}')
    lines.append('')
    lines.append('} // anonymous namespace')
    lines.append('')

    # Public API implementations
    lines.append('UNICODE_CODEPOINT toUppercase(UNICODE_CODEPOINT cp) {')
    lines.append('    return lookupMapping(uppercaseTable, uppercaseCount, cp);')
    lines.append('}')
    lines.append('')

    lines.append('UNICODE_CODEPOINT toLowercase(UNICODE_CODEPOINT cp) {')
    lines.append('    return lookupMapping(lowercaseTable, lowercaseCount, cp);')
    lines.append('}')
    lines.append('')

    lines.append('UNICODE_CODEPOINT toTitlecase(UNICODE_CODEPOINT cp) {')
    lines.append('    return lookupMapping(titlecaseTable, titlecaseCount, cp);')
    lines.append('}')
    lines.append('')

    lines.append('UNICODE_CODEPOINT toMirror(UNICODE_CODEPOINT cp) {')
    lines.append('    return lookupMapping(mirrorTable, mirrorCount, cp);')
    lines.append('}')
    lines.append('')

    lines.append('void toUppercase(UNICODE_CODEPOINT* buf, size_t len) {')
    lines.append('    for (size_t i = 0; i < len; i++) {')
    lines.append('        buf[i] = toUppercase(buf[i]);')
    lines.append('    }')
    lines.append('}')
    lines.append('')

    lines.append('void toLowercase(UNICODE_CODEPOINT* buf, size_t len) {')
    lines.append('    for (size_t i = 0; i < len; i++) {')
    lines.append('        buf[i] = toLowercase(buf[i]);')
    lines.append('    }')
    lines.append('}')
    lines.append('')

    lines.append('} // namespace UnicodeMappings')
    lines.append('')

    # Write output
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated {output_path}")
    print(f"  Uppercase mappings: {len(uppercase)}")
    print(f"  Lowercase mappings: {len(lowercase)}")
    print(f"  Titlecase mappings: {len(titlecase)}")
    print(f"  Mirror mappings: {len(mirror)}")

def main():
    parser = argparse.ArgumentParser(description='Generate UnicodeMappings.cpp')
    parser.add_argument('--output', '-o',
                        default='../../components/focus/src/text/UnicodeMappings.cpp',
                        help='Output file path')
    args = parser.parse_args()

    print("Parsing UnicodeData.txt...")
    uppercase, lowercase, titlecase = parse_unicode_data()

    print("Parsing BidiMirroring.txt...")
    mirror = parse_bidi_mirroring()

    generate_cpp(uppercase, lowercase, titlecase, mirror, args.output)

if __name__ == '__main__':
    main()
