#!/usr/bin/env python3
# MIT License
#
# Copyright (c) 2026 Joey Castillo
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""
Generate UnicodeArabicPresentation.cpp - Arabic letter shaping lookup table.

Arabic letters take different forms depending on their position in a word:
- Isolated: standalone letter
- Initial: beginning of a word
- Medial: middle of a word
- Final: end of a word

This script parses UnicodeData.txt to find Arabic Presentation Forms and builds
a lookup table mapping base Arabic characters (U+0621-U+06D2) to their shaped
forms in the Arabic Presentation Forms blocks (U+FB50-U+FEFF).

Usage:
    python3 generate_arabic.py [--output PATH]
"""

import argparse

# Arabic base character range
ARABIC_START = 0x0621
ARABIC_END = 0x06D2

# Form name suffixes used in Unicode character names
FORM_SUFFIXES = [
    ' ISOLATED FORM',
    ' INITIAL FORM',
    ' MEDIAL FORM',
    ' FINAL FORM'
]

def parse_unicode_data():
    """Parse UnicodeData.txt for character names."""
    names = {}
    with open('UnicodeData.txt', 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            fields = line.split(';')
            if len(fields) < 2:
                continue
            try:
                codepoint = int(fields[0], 16)
                name = fields[1]
                names[codepoint] = name
            except ValueError:
                continue
    return names

def build_arabic_lookup(names):
    """Build the Arabic presentation forms lookup table."""
    # Initialize lookup table: 179 entries (0x0621-0x06D2), 4 forms each
    table_size = ARABIC_END - ARABIC_START + 1
    lookup = [[0, 0, 0, 0] for _ in range(table_size)]

    # Get names of base Arabic characters
    base_names = {}
    for cp in range(ARABIC_START, ARABIC_END + 1):
        if cp in names:
            base_names[cp] = names[cp]

    # Search Arabic Presentation Forms blocks for matching forms
    # FB50-FDFF: Arabic Presentation Forms-A
    # FE70-FEFF: Arabic Presentation Forms-B
    for pf_cp in list(range(0xFB50, 0xFE00)) + list(range(0xFE70, 0xFF00)):
        if pf_cp not in names:
            continue

        pf_name = names[pf_cp]

        # Check each form suffix
        for form_idx, suffix in enumerate(FORM_SUFFIXES):
            if pf_name.endswith(suffix):
                # Extract base name
                base_name = pf_name[:-len(suffix)]

                # Find matching base character
                for base_cp, bn in base_names.items():
                    if bn == base_name:
                        table_idx = base_cp - ARABIC_START
                        lookup[table_idx][form_idx] = pf_cp
                        break

    return lookup

def generate_cpp(lookup, output_path):
    """Generate the C++ source file."""
    lines = []
    lines.append('/*')
    lines.append(' * UnicodeArabicPresentation.cpp - Arabic letter shaping lookup table')
    lines.append(' *')
    lines.append(' * AUTO-GENERATED FILE - DO NOT EDIT')
    lines.append(' * Generated by components/focus/tools/unicodedata/generate_arabic.py')
    lines.append(' *')
    lines.append(' * Arabic letters take different forms depending on position:')
    lines.append(' * - Isolated: standalone')
    lines.append(' * - Initial: beginning of word')
    lines.append(' * - Medial: middle of word')
    lines.append(' * - Final: end of word')
    lines.append(' *')
    lines.append(' * Note: Lam-Alef ligatures are NOT in this table.')
    lines.append(' * Implementations must handle these manually:')
    lines.append(' *   U+0644 + U+0622 => U+FEF5 (isolated) / U+FEF6 (final)')
    lines.append(' *   U+0644 + U+0623 => U+FEF7 (isolated) / U+FEF8 (final)')
    lines.append(' *   U+0644 + U+0625 => U+FEF9 (isolated) / U+FEFA (final)')
    lines.append(' *   U+0644 + U+0627 => U+FEFB (isolated) / U+FEFC (final)')
    lines.append(' */')
    lines.append('')
    lines.append('#include "UnicodeArabicPresentation.hpp"')
    lines.append('')
    lines.append('namespace UnicodeArabicPresentation {')
    lines.append('')
    lines.append('namespace {')
    lines.append('')
    lines.append(f'// Base range: U+{ARABIC_START:04X} to U+{ARABIC_END:04X}')
    lines.append(f'static constexpr UNICODE_CODEPOINT BASE_START = 0x{ARABIC_START:04X};')
    lines.append(f'static constexpr UNICODE_CODEPOINT BASE_END = 0x{ARABIC_END:04X};')
    lines.append('')
    lines.append('// Lookup table: [codepoint - BASE_START][form]')
    lines.append('// Forms: 0=Isolated, 1=Initial, 2=Medial, 3=Final')
    lines.append('// Value of 0 means form not available')
    lines.append('static const uint16_t presentationForms[][4] = {')

    for i, forms in enumerate(lookup):
        base_cp = ARABIC_START + i
        comment = f'// U+{base_cp:04X}'
        form_strs = [f'0x{f:04X}' if f else '0' for f in forms]
        lines.append(f'    {{{", ".join(form_strs)}}}, {comment}')

    lines.append('};')
    lines.append('')
    lines.append('} // anonymous namespace')
    lines.append('')

    # Public API implementations
    lines.append('bool isShapeable(UNICODE_CODEPOINT cp) {')
    lines.append('    if (cp < BASE_START || cp > BASE_END) return false;')
    lines.append('    // Check if any form exists')
    lines.append('    const uint16_t* forms = presentationForms[cp - BASE_START];')
    lines.append('    return forms[0] != 0;  // Isolated form indicates shapeability')
    lines.append('}')
    lines.append('')

    lines.append('UNICODE_CODEPOINT getForm(UNICODE_CODEPOINT base, Form form) {')
    lines.append('    if (base < BASE_START || base > BASE_END) return 0;')
    lines.append('    return presentationForms[base - BASE_START][static_cast<int>(form)];')
    lines.append('}')
    lines.append('')

    lines.append('} // namespace UnicodeArabicPresentation')
    lines.append('')

    # Write output
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    # Count entries with forms
    shapeable_count = sum(1 for forms in lookup if forms[0] != 0)
    total_forms = sum(sum(1 for f in forms if f != 0) for forms in lookup)

    print(f"Generated {output_path}")
    print(f"  Table entries: {len(lookup)}")
    print(f"  Shapeable characters: {shapeable_count}")
    print(f"  Total presentation forms: {total_forms}")

def main():
    parser = argparse.ArgumentParser(description='Generate UnicodeArabicPresentation.cpp')
    parser.add_argument('--output', '-o',
                        default='../../components/focus/src/text/UnicodeArabicPresentation.cpp',
                        help='Output file path')
    args = parser.parse_args()

    print("Parsing UnicodeData.txt...")
    names = parse_unicode_data()

    print("Building Arabic presentation lookup table...")
    lookup = build_arabic_lookup(names)

    generate_cpp(lookup, args.output)

if __name__ == '__main__':
    main()
